### ISSUE TITLE
домены с ??? или иероглифами

### ISSUE THREAD

**Issue by AndreySavenkov** [max197616/nfqfilter_config#1]
23.05.2016 в выгрузке появились URL следующего вида:

betcity.???
betcity.中文网

при перечитывании конфига nfqfilter вываливается с ошибкой:

2016-05-24 12:25:43.941 [8122] Fatal Application - Bad url format in line 26704 in file /etc/nfq/contrib/urls

на данный момент решил данную проблему удалением конкретно этих двух строк через sed перед перезапуском nfqfilter

**Comment by max197616** [comment]
Исправлено в последнем коммите.
